language: rust
cache: cargo
sudo: false
os:
    - linux
    - osx
before_script: (cargo install rustfmt || true)
script:
- |
  export PATH=$PATH:~/.cargo/bin &&
  cargo build &&
  cargo test &&
  cargo fmt -- --write-mode=diff
